import type { Metadata } from "next";
export const metadata: Metadata = { title: "开发者与数据接入", description: "公开 API、Atom Feed、商家 JSON Feed 与 Connector 接入说明。", alternates: { canonical: "/developers" } };
const endpoints=[
["GET /api/v1/products","标准产品卡片、可信最低价、官方参考与数据质量。"],
["GET /api/v1/catalog/groups","跨产品同款报价目录，支持交付、期限、质保、库存、更新时间和价格区间筛选。"],
["GET /api/v1/products/{slug}","产品详情、同款报价、90 天聚合价格与库存趋势。"],
["GET /api/v1/corrections","已解决且允许公开的纠错摘要，不返回联系方式和原始私密内容。"],
["GET /api/v1/watch.atom","无需账号的价格与补货 Atom Feed。"],
];
export default function DevelopersPage(){return <main id="main-content" className="shell py-12"><header className="max-w-5xl border-b border-black pb-10"><p className="mono text-xs tracking-[.15em] text-black/45">Developers / Connectors</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.06em] sm:text-6xl">把来源接入同一套证据模型</h1><p className="mt-6 max-w-4xl text-base leading-7 text-[color:var(--muted)]">项目提供只读公开 API、Atom 订阅、LDXP Connector 与通用商家 JSON Feed Connector。接口当前不承诺商业 SLA，请遵守缓存和合理请求频率。</p></header><section className="py-10"><h2 className="text-3xl font-semibold">公开 API</h2><div className="mt-5 overflow-hidden rounded-[18px] border hairline">{endpoints.map(([method,copy])=><div key={method} className="grid gap-2 border-b hairline bg-[color:var(--panel)] p-5 last:border-b-0 md:grid-cols-[280px_1fr]"><code className="text-sm font-semibold">{method}</code><p className="text-sm leading-6 text-black/55">{copy}</p></div>)}</div></section><section className="grid gap-6 border-t border-black py-10 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">商家 JSON Feed</h2><p className="mt-3 text-sm leading-7 text-black/60">Feed 可返回商品数组，或包含 shop、updated_at、items 的对象。商品至少提供稳定 ID、名称和来源 URL；价格、库存、类别与公开描述按统一导入模型处理。</p><a href="/shops/submit" className="mt-5 inline-block rounded-[10px] bg-[color:var(--ink)] px-5 py-3 text-sm text-white">提交 Feed 地址</a></div><div><h2 className="text-2xl font-semibold">Connector SDK 基础</h2><p className="mt-3 text-sm leading-7 text-black/60">后端 Connector 接口统一输出标准化记录。新增来源应实现读取、校验和转换，不直接写业务数据库；发布流程继续使用幂等导入和原子快照。</p><a href="https://github.com/BeterXie/ai_price_radar/tree/main/pipeline/connectors" target="_blank" rel="noreferrer" className="mt-5 inline-block rounded-[10px] border border-black px-5 py-3 text-sm">查看 Connector 代码</a></div></section></main>}
