FROM caddy:2-alpine

ARG ALPINE_REPOSITORY_HOST=dl-cdn.alpinelinux.org
RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_REPOSITORY_HOST}/g" /etc/apk/repositories \
    && apk add --no-cache nodejs

WORKDIR /app
ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

COPY --chown=nobody:nobody public ./public
COPY --chown=nobody:nobody .next/standalone ./
COPY --chown=nobody:nobody .next/static ./.next/static

EXPOSE 3000
USER nobody
CMD ["node", "server.js"]
