import type {
  BrandSlug,
  KnownDeliveryType,
  OfficialSource,
  ProductGuide,
  ProductSlug,
} from "@/lib/guides/types";
import { GUIDE_DISCLAIMER, LAST_REVIEWED_AT, OFFICIAL_SOURCES } from "./sources";

const DELIVERY_LABELS: Record<KnownDeliveryType, string> = {
  subscription_recharge: "订阅充值",
  finished_account: "成品账号",
  semi_finished_account: "半成品账号",
  team_seat: "团队席位",
  card_code: "卡密或兑换码",
  api_credit: "API Key 与额度",
  verification_service: "验证辅助服务",
  shared_pool: "共享账号或共享池",
  relay_api: "第三方 API 中转",
  trial_account: "短期体验账号",
};

interface ProductSeed {
  productSlug: ProductSlug;
  brand: BrandSlug;
  title: string;
  description: string;
  summary: string;
  difference: string;
  audience: readonly string[];
  supportedDeliveryTypes: readonly KnownDeliveryType[];
  buyingNotes: readonly string[];
  verificationNotes: readonly string[];
  riskNotes: readonly string[];
  faq: { question: string; answer: string };
  officialSources: readonly OfficialSource[];
  securityProfile: "account" | "api" | "verification";
}

const productSeeds = [
  {
    productSlug: "chatgpt-account",
    brand: "openai",
    title: "ChatGPT Free 与基础账号指南",
    description: "了解 ChatGPT 基础账号的成品号、半成品号、体验号、共享池和验证辅助之间的差异。",
    summary: "ChatGPT Free 是不以付费套餐为前提的基础账号目录；第三方市场主要出售账号或短期访问，而不是 Plus、Go 或 Pro 权益。",
    difference: "本页不包含明确的 Plus、Go、Pro、团队席位、Codex 或 API 商品；是否带付费权益必须从官方账户页核对。",
    audience: ["需要先体验 ChatGPT 基础功能的用户", "正在比较账号控制权与短期访问风险的用户"],
    supportedDeliveryTypes: ["finished_account", "semi_finished_account", "trial_account", "shared_pool", "verification_service"],
    buyingNotes: ["确认商品没有把普通账号描述成付费套餐。", "确认登录方式、注册邮箱、恢复渠道与质保。"],
    verificationNotes: ["官方账户页应显示正确账号；若显示 Free，代表未确认任何付费套餐。"],
    riskNotes: ["基础账号也可能被原注册者找回，低价不代表控制权完整。"],
    faq: { question: "ChatGPT Free 账号包含 Plus 吗？", answer: "不包含。只有官方账户页明确显示 Plus 等付费套餐时，才能确认对应权益。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-plus",
    brand: "openai",
    title: "ChatGPT Plus 购买与使用指南",
    description: "区分自有账号代充、成品号、半成品号、兑换码、共享池和体验号，并确认 Plus 是否生效。",
    summary: "ChatGPT Plus 是个人 ChatGPT 付费套餐；第三方报价的价格差异通常来自账号归属、交付形式、期限与质保，而非同一种标准商品。",
    difference: "Plus 与 Free、Go、Pro、团队席位及 API 分别管理；API 用量不包含在 Plus 中。",
    audience: ["希望提升个人 ChatGPT 使用体验的用户", "需要判断代充与账号交付区别的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "semi_finished_account", "card_code", "shared_pool", "trial_account"],
    buyingNotes: ["确认商品明确写明 Plus、期限和账号归属。", "共享与体验报价不能和长期独享 Plus 直接比较。"],
    verificationNotes: ["在 ChatGPT 官方设置中确认当前账号显示 Plus、正确期限与续费状态。"],
    riskNotes: ["代充前充错账号、共享会话暴露和成品号找回是不同风险，应按交付形式分别判断。"],
    faq: { question: "代充完成但仍显示 Free 怎么办？", answer: "核对登录账号与约定到账时间，保存官方套餐页和订单截图后联系原商家。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-go",
    brand: "openai",
    title: "ChatGPT Go 购买与使用指南",
    description: "核对 ChatGPT Go 的订阅充值、成品账号或兑换码交付，避免与 Plus、Pro 和基础账号混淆。",
    summary: "ChatGPT Go 在目录中作为独立套餐处理；商品必须明确指向 Go，不能因为价格或描述相似就按 Plus 或 Pro 理解。",
    difference: "Go 与 Free、Plus、Pro 是不同套餐；功能和可用资格可能变化，以 OpenAI 官方账户页为准。",
    audience: ["商品原文明确购买 ChatGPT Go 的用户", "需要确认 Go 套餐到账和账号归属的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "card_code"],
    buyingNotes: ["标题与商品说明都应明确写明 Go。", "核对兑换资格、订阅期限和目标账号。"],
    verificationNotes: ["在官方账户页确认套餐名称为商品约定的 Go，而不是 Free、Plus 或 Pro。"],
    riskNotes: ["套餐资格与兑换条件以官方规则为准，不应通过第三方说明推断可用地区。"],
    faq: { question: "Go 可以按 Plus 的权益判断吗？", answer: "不可以。两个套餐应分别核对名称、功能、期限与官方资格。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-k12",
    brand: "openai",
    title: "ChatGPT Team、Business 与 K12 指南",
    description: "了解团队邀请、工作区席位和带席位账号的差异，确认管理员权限、组织名称和退出路径。",
    summary: "当前目录用 K12 口径收纳明确的 Team、Business、团队席位、车位与邀请商品，核心交付是组织工作区访问。",
    difference: "团队席位由组织管理员分配，不是个人 Plus 或 Pro，也不等于获得工作区所有权。",
    audience: ["准备加入第三方 ChatGPT 工作区的用户", "需要区分席位与完整账号交付的用户"],
    supportedDeliveryTypes: ["team_seat", "finished_account"],
    buyingNotes: ["确认邀请来源、组织名称、管理员、期限及被移除后的售后。", "确认使用自己的账号加入还是收到带席位账号。"],
    verificationNotes: ["官方工作区切换处应显示正确组织；确认目标功能可用并知道如何退出。"],
    riskNotes: ["管理员可管理或移除席位，不要在第三方工作区存放公司机密。"],
    faq: { question: "团队席位等于拥有账号吗？", answer: "不等于。席位只是组织授予的权限，账号控制权和工作区管理权需要分别确认。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-pro-5x",
    brand: "openai",
    title: "ChatGPT Pro 5x 指南",
    description: "比较明确标注 Pro 5x 的充值、成品号、半成品号、共享池与体验号，核验实际套餐和限制。",
    summary: "Pro 5x 是第三方商品目录中的明确倍率口径；本站不替商家推断其具体权益，购买前必须查看原商品说明。",
    difference: "只有明确标注 5x 的商品进入本页；未注明倍率的 Pro 留在通用 Pro，20x 则进入独立目录。",
    audience: ["商品明确标注 Pro 5x 的用户", "需要比较独享、共享与短期 Pro 访问的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "semi_finished_account", "shared_pool", "trial_account"],
    buyingNotes: ["核对 5x 权益的商品原文、周期和限制。", "共享池或体验号不能视为长期独享 Pro。"],
    verificationNotes: ["从官方账户页确认 Pro 套餐；5x 商品口径还需与下单时保存的原商品说明对照。"],
    riskNotes: ["倍率口径可能来自第三方商品描述，不能代替官方套餐状态。"],
    faq: { question: "没有明确 5x 的 Pro 会出现在这里吗？", answer: "不会。倍率不明确时应查看通用 ChatGPT Pro 指南。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-pro-20x",
    brand: "openai",
    title: "ChatGPT Pro 20x 指南",
    description: "比较明确标注 Pro 20x 的多种账号与充值交付，确认倍率说明、期限、账号控制权和套餐状态。",
    summary: "Pro 20x 是目录对明确倍率商品的独立分类；交付可能是充值、账号、共享池或短期访问，风险不能混为一类。",
    difference: "20x 与 5x、未明确倍率的 Pro 分开；价格不能在不同倍率与交付形式间直接横比。",
    audience: ["商品明确标注 Pro 20x 的用户", "需要核对高倍率商品交付边界的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "semi_finished_account", "shared_pool", "trial_account"],
    buyingNotes: ["保存写明 20x 权益、期限和限制的原商品页。", "确认账号是独享、共享还是短期使用。"],
    verificationNotes: ["官方页面应显示 Pro 套餐；商品声明的倍率需结合原页面和实际限制另行核对。"],
    riskNotes: ["明显低价可能来自共享或短期权限，不代表完整长期 Pro 20x。"],
    faq: { question: "20x 和 5x 可以只按总价比较吗？", answer: "不建议。先统一倍率口径、期限、交付形式和控制权，再比较价格。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "chatgpt-pro",
    brand: "openai",
    title: "ChatGPT Pro 指南",
    description: "了解未明确 5x 或 20x 倍率的 ChatGPT Pro 充值与账号交付，避免替商品推断权益。",
    summary: "通用 ChatGPT Pro 目录收纳明确写明 Pro、但信息不足以判断 5x 或 20x 的商品。",
    difference: "倍率明确的商品进入 5x 或 20x 专页；Plus、Go、团队席位与 Pro 也不是同一套餐。",
    audience: ["购买未明确倍率 ChatGPT Pro 的用户", "需要回到商品原文确认权益口径的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "semi_finished_account", "shared_pool", "trial_account"],
    buyingNotes: ["要求商品原文明确套餐、期限和限制，不根据低价猜测倍率。", "区分独享账号、共享池与体验号。"],
    verificationNotes: ["官方账户页应显示 Pro；任何额外倍率说明以保存的原商品页面为证。"],
    riskNotes: ["权益描述不清时不应按 5x 或 20x 预期使用，也不应与其直接比较。"],
    faq: { question: "为什么没有自动判断 5x 或 20x？", answer: "商品没有明确倍率时，系统不会代替商家猜测权益。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "account",
  },
  {
    productSlug: "openai-api-credit",
    brand: "openai",
    title: "OpenAI API Key 与额度指南",
    description: "区分官方 API 额度、兑换口径和第三方中转，安全保存 Key、设置预算并处理泄露。",
    summary: "OpenAI API 按项目与用量管理，和 ChatGPT 网页会员是不同服务；第三方报价可能按余额、额度、时间或中转倍率计价。",
    difference: "ChatGPT Plus、Go、Pro 或团队席位不会自动提供 OpenAI API 额度；第三方中转也不是官方 API。",
    audience: ["需要通过程序调用 OpenAI 模型的开发者", "正在比较官方额度、卡密与第三方中转的用户"],
    supportedDeliveryTypes: ["api_credit", "relay_api", "card_code"],
    buyingNotes: ["核对官方或第三方服务身份、额度单位、模型、有效期、并发和撤销权。", "确认谁控制项目、账单、预算与 API Key。"],
    verificationNotes: ["先用非敏感最小请求确认模型与扣量，再在控制台查看用量、预算和提醒。"],
    riskNotes: ["第三方售卖的 Key 可能被多人共享或撤销；中转方可能处理请求数据。"],
    faq: { question: "OpenAI API 额度等于 ChatGPT Plus 吗？", answer: "不等于。API 与 ChatGPT 网页订阅分别管理和计费。" },
    officialSources: [OFFICIAL_SOURCES.openaiKeySafety, OFFICIAL_SOURCES.openaiPlatform],
    securityProfile: "api",
  },
  {
    productSlug: "chatgpt-access-service",
    brand: "openai",
    title: "ChatGPT 与 Codex 开通辅助服务指南",
    description: "理解注册或验证辅助的服务边界，优先使用官方流程，不提交敏感凭据或寻求绕过验证。",
    summary: "本目录收纳与 ChatGPT、Codex 相关的合规开通咨询或验证辅助，不是账号、订阅、API 额度或长期控制权。",
    difference: "辅助服务只处理约定环节，不应被当作 Plus、Pro、Codex 账号或 API 商品。",
    audience: ["需要先判断辅助服务到底交付什么的用户", "遇到官方注册或验证提示并寻找合规帮助的用户"],
    supportedDeliveryTypes: ["verification_service"],
    buyingNotes: ["确认服务合法、合规并符合平台规则。", "拒绝要求验证码、恢复码、密码、证件或规避安全机制的流程。"],
    verificationNotes: ["最终只从 OpenAI 官方页面确认账号状态和本人控制的恢复渠道。"],
    riskNotes: ["验证成功不等于长期账号控制权；本站不提供接码或自动化绕过教程。"],
    faq: { question: "开通辅助等于购买账号吗？", answer: "不等于。交付仅限商品原文约定的辅助环节，不自动包含账号或订阅。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiTerms],
    securityProfile: "verification",
  },
  {
    productSlug: "codex-access",
    brand: "openai",
    title: "Codex 账号与访问指南",
    description: "区分 Codex 的完整账号、订阅权限和团队席位，核对登录主体、组织、使用环境与控制权。",
    summary: "Codex 商品可能交付可登录账号、为现有账号开通的访问权限，或组织工作区中的席位。",
    difference: "Codex 访问不应与 OpenAI API 额度、ChatGPT Plus 或第三方中转自动画等号，具体权限以官方账号和组织显示为准。",
    audience: ["需要在开发工作流中使用 Codex 的用户", "正在比较个人账号、充值和团队席位的用户"],
    supportedDeliveryTypes: ["finished_account", "subscription_recharge", "team_seat"],
    buyingNotes: ["确认可用环境、登录账号、组织名称、期限和权限来源。", "团队席位需确认管理员与被移除后的处理。"],
    verificationNotes: ["在官方入口确认当前账号或组织拥有 Codex 访问，并用非敏感仓库完成最小测试。"],
    riskNotes: ["不要让第三方 Codex 账号访问私有代码、生产密钥或公司机密。"],
    faq: { question: "Codex 访问一定包含 OpenAI API 额度吗？", answer: "不一定。账号或组织访问与 API 项目额度需要分别核对。" },
    officialSources: [OFFICIAL_SOURCES.openaiHelp, OFFICIAL_SOURCES.openaiPlatform],
    securityProfile: "account",
  },
  {
    productSlug: "claude-pro",
    brand: "claude",
    title: "Claude Pro 购买与使用指南",
    description: "区分 Claude Pro 代充、成品号、半成品号与兑换码，核对套餐、期限、登录方式和账号控制权。",
    summary: "Claude Pro 是个人 Claude 网页付费套餐；第三方交付可能改变账号控制权，但不会把网页订阅变成 API 额度。",
    difference: "Claude 基础账号未必包含 Pro，Claude API 则在 Console 单独管理和计费。",
    audience: ["需要 Claude 个人付费套餐的用户", "比较代充与账号交付风险的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "semi_finished_account", "card_code"],
    buyingNotes: ["确认商品明确写明 Claude Pro、账号归属、期限和续费。", "确认登录方式与注册邮箱控制权。"],
    verificationNotes: ["在 Claude 官方设置中核对 Pro 状态、目标账号和可用功能。"],
    riskNotes: ["账号地区、验证与恢复渠道可能影响可持续访问；不要寻求规避官方限制。"],
    faq: { question: "Claude Pro 是否包含 Claude API？", answer: "不包含。Anthropic API 需要通过 Console 单独设置并按用量计费。" },
    officialSources: [OFFICIAL_SOURCES.anthropicHelp, OFFICIAL_SOURCES.anthropicTerms],
    securityProfile: "account",
  },
  {
    productSlug: "claude-account",
    brand: "claude",
    title: "Claude 基础账号指南",
    description: "了解 Claude 基础成品号、半成品号、体验号、共享池和验证辅助，不把普通账号误作 Pro。",
    summary: "Claude 基础账号目录收纳未确认 Pro 权益的账号类商品，主要差异是登录、控制权、期限与共享方式。",
    difference: "明确的 Claude Pro 和 Claude API 有独立目录；普通账号不能按付费套餐或 API 权益使用。",
    audience: ["只需体验 Claude 基础功能的用户", "核对短期、共享和完整账号差异的用户"],
    supportedDeliveryTypes: ["finished_account", "semi_finished_account", "trial_account", "shared_pool", "verification_service"],
    buyingNotes: ["确认是否带 Pro、能否修改资料、登录方式和质保。", "共享与体验账号不适合敏感或长期内容。"],
    verificationNotes: ["从 Claude 官方账户页确认账号和实际套餐，不根据商品名称推断 Pro。"],
    riskNotes: ["普通账号也可能被找回或受登录验证影响。"],
    faq: { question: "Claude 账号一定有 Pro 吗？", answer: "不一定。商品与官方账户页都需明确显示 Pro 才能确认。" },
    officialSources: [OFFICIAL_SOURCES.anthropicHelp, OFFICIAL_SOURCES.anthropicTerms],
    securityProfile: "account",
  },
  {
    productSlug: "claude-api-access",
    brand: "claude",
    title: "Claude API 指南",
    description: "区分 Anthropic 官方 API 额度与第三方中转，保护 Key、监控用量并避免处理敏感数据。",
    summary: "Claude API 面向程序调用，通过 Anthropic Console 单独管理；第三方商品可能按额度、时间或代理访问销售。",
    difference: "Claude Pro 是网页订阅，不包含 API 用量；中转服务也不属于 Anthropic 官方 API。",
    audience: ["通过程序调用 Claude 的开发者", "需要判断官方额度和中转数据边界的用户"],
    supportedDeliveryTypes: ["api_credit", "relay_api"],
    buyingNotes: ["核对 API 运营方、模型、额度单位、速率限制、期限和撤销方式。", "确认预算、账单提醒和日志处理规则。"],
    verificationNotes: ["以非敏感最小请求确认模型和扣量，并在 Console 或第三方控制台核对用量。"],
    riskNotes: ["中转请求会经过第三方服务器，不能用于敏感、受监管或保密数据。"],
    faq: { question: "Claude API 与 Claude Pro 是同一服务吗？", answer: "不是。网页订阅和 API 访问分别管理和计费。" },
    officialSources: [OFFICIAL_SOURCES.anthropicDocs, OFFICIAL_SOURCES.anthropicHelp],
    securityProfile: "api",
  },
  {
    productSlug: "gemini-advanced",
    brand: "gemini",
    title: "Gemini Advanced 与 Google AI 套餐指南",
    description: "区分 Gemini Advanced 的账号充值、成品号和兑换码交付，核对 Google 账号、套餐与订阅状态。",
    summary: "Gemini Advanced 作为 Google 账号中的付费 AI 权益，需要从 Gemini 或 Google 官方订阅页面确认。",
    difference: "Gemini 基础账号不保证 Advanced 权益；Gemini API 也采用独立的开发者项目与额度。",
    audience: ["需要 Gemini 付费功能的个人用户", "比较 Google 账号代充、账号和兑换码的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "card_code"],
    buyingNotes: ["核对目标 Google 账号、套餐名称、期限和自动续费。", "兑换码需确认账号资格、地区与有效期。"],
    verificationNotes: ["在 Google 官方订阅或 Gemini 设置中确认正确账号、套餐与到期状态。"],
    riskNotes: ["第三方 Google 账号可能关联邮箱、云盘和个人数据，控制权风险高于单一 AI 账号。"],
    faq: { question: "Gemini Advanced 是否等于 Gemini API 额度？", answer: "不等于。Gemini Apps 订阅和开发者 API 分别管理。" },
    officialSources: [OFFICIAL_SOURCES.geminiHelp, OFFICIAL_SOURCES.googleAccount],
    securityProfile: "account",
  },
  {
    productSlug: "gemini-account",
    brand: "gemini",
    title: "Gemini 基础账号指南",
    description: "了解 Gemini 成品号、半成品号和验证辅助，确认 Google 账号归属、登录方式和隐私边界。",
    summary: "Gemini 基础账号通常依赖 Google 账号，本页不把普通 Gmail、Advanced 订阅或 API 额度混在一起。",
    difference: "Advanced 是付费权益，Gemini API 是开发者服务；基础账号只按实际官方状态理解。",
    audience: ["需要体验 Gemini 基础功能的用户", "正在核对第三方 Google 账号控制权的用户"],
    supportedDeliveryTypes: ["finished_account", "semi_finished_account", "verification_service"],
    buyingNotes: ["确认账号确实面向 Gemini、登录方式和邮箱恢复渠道。", "不要把普通邮箱商品误作 Advanced 套餐。"],
    verificationNotes: ["在 Gemini 官方页面确认可访问，并在 Google 账号页核对账号标识与安全设置。"],
    riskNotes: ["Google 账号可能连接其他服务，不应使用第三方账号处理邮箱、云盘或身份敏感数据。"],
    faq: { question: "Gemini 基础账号包含 Advanced 吗？", answer: "不一定。必须从官方订阅状态确认，不能仅凭账号可登录判断。" },
    officialSources: [OFFICIAL_SOURCES.geminiHelp, OFFICIAL_SOURCES.googleAccount],
    securityProfile: "account",
  },
  {
    productSlug: "gemini-api-access",
    brand: "gemini",
    title: "Gemini API 指南",
    description: "区分 Gemini 官方 API 额度与第三方中转，安全管理 API Key、项目、预算和请求数据。",
    summary: "Gemini API 面向开发者程序调用，额度、模型和速率限制与 Gemini Apps 的账号或 Advanced 订阅分开。",
    difference: "Advanced 会员不能代替 API 额度；第三方中转也不能按 Google 官方 API 的数据边界理解。",
    audience: ["需要集成 Gemini API 的开发者", "比较官方 API 和中转服务的用户"],
    supportedDeliveryTypes: ["api_credit", "relay_api"],
    buyingNotes: ["确认项目归属、模型、额度、有效期、速率限制和账单控制。", "了解第三方服务的日志与数据处理规则。"],
    verificationNotes: ["用非敏感测试请求核对模型和扣量，并查看项目用量、预算与提醒。"],
    riskNotes: ["第三方中转可能读取输入和输出，不发送个人、企业或受监管信息。"],
    faq: { question: "Gemini API 能直接使用 Advanced 订阅额度吗？", answer: "不能按此假设。API 项目和 Gemini Apps 订阅是不同体系。" },
    officialSources: [OFFICIAL_SOURCES.geminiApi, OFFICIAL_SOURCES.geminiHelp],
    securityProfile: "api",
  },
  {
    productSlug: "grok-super",
    brand: "grok",
    title: "SuperGrok 购买与使用指南",
    description: "区分 SuperGrok 订阅充值、成品账号和兑换码，核对主商品、账号归属、周期与官方套餐。",
    summary: "SuperGrok 是 xAI 付费产品目录；某些商品可能描述关联权益，但主商品与 X Premium 仍需分开判断。",
    difference: "普通 Grok 账号、xAI API 与 X Premium 各有独立目录，不能仅因附带权益混为一种商品。",
    audience: ["明确购买 SuperGrok 的用户", "需要区分账号、充值和兑换码交付的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account", "card_code"],
    buyingNotes: ["确认主商品写明 SuperGrok、期限、账号与续费规则。", "核对兑换资格和账号控制权。"],
    verificationNotes: ["从 xAI 官方账户或产品页面确认 SuperGrok 状态与目标账号。"],
    riskNotes: ["附赠或关联权益不代表同时拥有另一产品的完整订阅。"],
    faq: { question: "包含 X 权益时就应按 X Premium 购买吗？", answer: "不应自动这样判断。先确认商品主标题和官方账户实际显示的产品。" },
    officialSources: [OFFICIAL_SOURCES.grokHelp, OFFICIAL_SOURCES.xHelp],
    securityProfile: "account",
  },
  {
    productSlug: "grok-account",
    brand: "grok",
    title: "Grok 基础账号指南",
    description: "了解 Grok 成品号、半成品号和短期体验号，确认付费权益、账号控制权、期限与隐私边界。",
    summary: "Grok 基础账号目录收纳未确认 SuperGrok 的账号商品，低价可能来自普通功能、短期有效期或受限账号。",
    difference: "SuperGrok、xAI API 和 X Premium 不在本页；基础账号不能按这些产品的权益使用。",
    audience: ["体验 Grok 基础功能的用户", "需要比较完整、半成品与短期账号的用户"],
    supportedDeliveryTypes: ["finished_account", "semi_finished_account", "trial_account"],
    buyingNotes: ["确认是否带付费权益、可用入口、期限、验证状态和质保。", "不要因极低价格推断为完整订阅。"],
    verificationNotes: ["从 xAI 官方页面确认账号可用和实际套餐；短期账号需同时核对起止时间。"],
    riskNotes: ["体验或第三方账号可能随时失效，不绑定重要资料或长期聊天记录。"],
    faq: { question: "低价 Grok 账号就是 SuperGrok 吗？", answer: "不是。只有商品和官方账户状态都明确时才能确认 SuperGrok。" },
    officialSources: [OFFICIAL_SOURCES.grokHelp],
    securityProfile: "account",
  },
  {
    productSlug: "grok-api-access",
    brand: "grok",
    title: "Grok API 指南",
    description: "比较 xAI 官方 API 额度与第三方中转，保护 API Key 并核对模型、用量、账单和数据处理。",
    summary: "Grok API 面向程序调用；报价可能表示官方额度或第三方中转访问，必须先统一单位与服务身份。",
    difference: "Grok 或 SuperGrok 网页账号不等于 xAI API 额度；中转服务也不是官方 API。",
    audience: ["集成 xAI 模型的开发者", "需要判断官方额度与中转风险的用户"],
    supportedDeliveryTypes: ["api_credit", "relay_api"],
    buyingNotes: ["核对服务方、模型、额度单位、有效期、并发、预算和撤销权。", "确认中转方如何处理日志、输入和输出。"],
    verificationNotes: ["用非敏感最小请求核对模型、响应和扣量，再检查控制台用量。"],
    riskNotes: ["中转数据可能由第三方处理；不发送机密、个人或受监管数据。"],
    faq: { question: "Grok 账号能直接当作 API 额度使用吗？", answer: "不能按此假设。网页账号和 xAI API 是不同的访问方式。" },
    officialSources: [OFFICIAL_SOURCES.grokApi, OFFICIAL_SOURCES.grokHelp],
    securityProfile: "api",
  },
  {
    productSlug: "x-premium-basic",
    brand: "x",
    title: "X Premium Basic 指南",
    description: "核对 X Premium Basic 的充值或成品账号交付，确认档位、账号、订阅周期和控制权。",
    summary: "Premium Basic 是 X Premium 产品系列中的独立档位，本页只按商品明确标注的 Basic 口径说明。",
    difference: "Premium Basic 不与 Premium、Premium+ 或 SuperGrok 混算，具体功能以 X 官方套餐页为准。",
    audience: ["明确购买 X Premium Basic 的用户", "需要比较自有账号充值和成品账号的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account"],
    buyingNotes: ["确认标题明确写明 Basic、目标 X 账号、周期和续费。", "成品账号需确认邮箱、恢复渠道和 MFA。"],
    verificationNotes: ["从 X 官方账户页核对账号和 Premium Basic 档位、期限与续费状态。"],
    riskNotes: ["X 账号可能包含私信和身份关系，第三方账号不用于私人或业务敏感活动。"],
    faq: { question: "Basic 可以按 Premium+ 权益使用吗？", answer: "不可以。三个档位应分别核对官方权益和状态。" },
    officialSources: [OFFICIAL_SOURCES.xHelp, OFFICIAL_SOURCES.xTerms],
    securityProfile: "account",
  },
  {
    productSlug: "x-premium",
    brand: "x",
    title: "X Premium 指南",
    description: "区分 X Premium 中间档的充值与成品账号，核对账号、周期、官方档位和续费状态。",
    summary: "X Premium 在本目录特指中间档位；即使商品提到 Grok 相关权益，仍需按主商品和官方状态判断。",
    difference: "Basic、Premium 和 Premium+ 分开统计；SuperGrok 也属于独立产品目录。",
    audience: ["明确购买 X Premium 中间档的用户", "需要确认充值和成品账号差异的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account"],
    buyingNotes: ["确认档位是 Premium 而非 Basic 或 Premium+。", "核对充值账号、地区条件、期限和退款范围。"],
    verificationNotes: ["在 X 官方设置中确认当前账号显示 Premium 档位和正确周期。"],
    riskNotes: ["代充充错账号与成品号被找回属于不同问题，应保存相应证据。"],
    faq: { question: "三个 X Premium 档位可以一起比最低价吗？", answer: "不建议。档位权益不同，应分别查看对应目录。" },
    officialSources: [OFFICIAL_SOURCES.xHelp, OFFICIAL_SOURCES.xTerms],
    securityProfile: "account",
  },
  {
    productSlug: "x-premium-plus",
    brand: "x",
    title: "X Premium+ 指南",
    description: "核对 X Premium+ 的充值与成品账号交付，确认加号档位、账号、周期、续费和控制权。",
    summary: "Premium+ 是 X Premium 产品系列中的独立高档位；标题中的加号和官方账户状态都需要明确。",
    difference: "Premium+ 不与 Premium、Basic 或以 SuperGrok 为主商品的报价混算。",
    audience: ["明确购买 X Premium+ 的用户", "需要核对高档位账号与代充交付的用户"],
    supportedDeliveryTypes: ["subscription_recharge", "finished_account"],
    buyingNotes: ["确认商品与官方页面都显示 Premium+，避免漏看加号。", "核对期限、目标账号、续费和售后。"],
    verificationNotes: ["从 X 官方账户页确认 Premium+ 档位、正确账号和订阅周期。"],
    riskNotes: ["样本少或价格偏低时更应核对交付形式，成品账号不等于拥有注册邮箱。"],
    faq: { question: "SuperGrok 附带 X 权益就属于 Premium+ 吗？", answer: "不一定。应按商品主标题和 X 官方账户实际显示的档位判断。" },
    officialSources: [OFFICIAL_SOURCES.xHelp, OFFICIAL_SOURCES.xTerms],
    securityProfile: "account",
  },
] as const satisfies readonly ProductSeed[];

const accountSafetyNotes = [
  "账号类交付必须确认邮箱、恢复渠道和 MFA 的控制权，能够登录不等于拥有账号。",
  "不要在第三方账号、共享池或短期账号中存放个人隐私、公司机密或支付信息。",
];

const apiSafetyNotes = [
  "API Key 不得写入前端、公开代码或代码仓库；使用环境变量或密钥管理服务。",
  "设置用量预算和账单提醒；Key 泄露时立即撤销并轮换，同时检查异常用量。",
];

function buildProductGuide(seed: ProductSeed): ProductGuide {
  const securityNotes = seed.securityProfile === "api"
    ? apiSafetyNotes
    : seed.securityProfile === "account"
      ? accountSafetyNotes
      : [
          "验证辅助不等于账号控制权；只通过官方页面处理本人账号。",
          "不要向本站或第三方提交密码、验证码、恢复码、身份证件或其他隐私凭据。",
        ];

  return {
    productSlug: seed.productSlug,
    brand: seed.brand,
    title: seed.title,
    description: seed.description,
    audience: seed.audience,
    supportedDeliveryTypes: seed.supportedDeliveryTypes,
    overview: [
      { type: "paragraph", text: seed.summary },
      {
        type: "comparison",
        title: "与相邻分类的区别",
        columns: ["当前教程", "分类边界"],
        rows: [[seed.title, seed.difference]],
      },
      { type: "checklist", title: "适合哪些用户", items: seed.audience },
      {
        type: "callout",
        tone: "info",
        title: "本页覆盖的第三方交付",
        text: seed.supportedDeliveryTypes.map((type) => DELIVERY_LABELS[type]).join("、"),
      },
    ],
    buyingChecklist: [
      `确认商品原页面明确指向“${seed.title.replace("指南", "")}”。`,
      "确认使用自己的账号还是商家提供的账号，并核对交付类型、期限、价格单位和质保。",
      "保存商品原页面、订单、交付时间和售后条件，不以本站摘要替代商家说明。",
      ...seed.buyingNotes,
    ],
    verificationChecklist: [
      "只在品牌官方页面核对当前登录账号、套餐或服务状态。",
      "保存经过隐私遮挡的账号状态、期限与错误提示，不展示密码、验证码、恢复码或完整 Key。",
      ...seed.verificationNotes,
    ],
    riskNotes: [
      ...seed.riskNotes,
      ...securityNotes,
      "不使用绕过地区、身份、短信、支付验证或平台风控的方法；遇到限制时改用官方支持。",
    ],
    faq: [
      seed.faq,
      {
        question: "售后需要准备什么？",
        answer: "准备商品原页面、订单与交付时间、经过遮挡的官方状态页、完整错误提示和沟通记录；不要发送密码、验证码、恢复码或完整 API Key。",
      },
    ],
    officialSources: seed.officialSources,
    disclaimer: GUIDE_DISCLAIMER,
    lastReviewedAt: LAST_REVIEWED_AT,
  };
}

export const productGuideEntries: readonly ProductGuide[] = productSeeds.map(buildProductGuide);
